### ISSUE TITLE
New event to get currently connected games and players

### ISSUE THREAD

**Issue by oestrich** [oestrich/gossip#16]
Part of the `players` support flag.

Request:

```json
{
  "events": "players/status",
  "ref": "c8cbaef2-b6e9-4110-b712-a312aee9e7d4"
}
```

`ref` is required.

Response:

```json
{
  "events": "players/status",
  "ref": "c8cbaef2-b6e9-4110-b712-a312aee9e7d4",
  "payload": {
    "MidMUD": ["eric"],
    "Myelin": ["Admin"],
    "Apotheosis": ["Adam"]
  }
}
```

**Comment by shanesveller** [comment]
Once many MUDs are heartbeating and/or a single large player list is involved, it might be desirable to report `players/status` with a per-game payload? Partially depends on how many events-per-second you feel like fanning out, and how many E/S peers feel like receiving.

```
{
  "events": "peer/status",
  "ref": "...",
  "payload": {
    "game": "MidMUD",
    "players: ["eric"]
  }
}
```
